agora/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password'),
]

agora/agora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('mypage/', include('mypage.urls')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('', views.index),
    path('parsed_data/', include('parsed_data.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agora/boards/urls.py
from django.urls import path
from . import views    # 동일한 디렉토리에 있는 views.py 를 import 하겠다.

# 여러 APP이 있을 경우 이름 공간을 분리하기 위해 아래와 같이 app의 이름을 지정한다.
# app_name 쓸 때 소문자로 써야함
app_name = 'boards'

# 경로 설정할 때 마지막에 꼭 '/' 가 들어가야 한다.
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name='comments_edit'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/like/', views.like, name='like'),
    path('<int:board_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

agora/chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

agora/mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('userprofile/<int:user_pk>/', views.userprofile, name='userprofile'),
]

agora/boards/models.py
from django.db import models
from django.conf import settings

class Board(models.Model):
    # Field 정의
    title = models.CharField(max_length=20) # 최대 입력 가능한 글자의 수 제한 여기서는 10글자
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # 처음 생성한 시간을 나타냄 (최초 한 번만 생성)
    updated_at = models.DateTimeField(auto_now=True)      # 수정한 시간을 나타냄
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # AUTH_USER_MODEL : 장고가 기본적으로 갖고 있는 유저 모델

    # blank 옵션은 좋아요를 누르지 않은 경우를 생각해서 True로 설정.
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards', blank=True)

    def __str__(self):
        return f'글 번호 -> {self.id}, 글 제목 -> {self.title}, 글 내용 -> {self.content}'



class DjangoBoard(models.Model):
    subject = models.CharField(max_length=50, blank=True)
    name = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    mail = models.CharField(max_length=50, blank=True)
    memo = models.CharField(max_length=200, blank=True)
    hits = models.IntegerField(null=True, blank=True)

# 댓글 달기를 위한 class 선언
class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments_rn')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'<Board{self.board_id}: Comment({self.id} - {self.content})>'

agora/mypage/models.py
from django.db import models

# Create your models here.

agora/boards/forms.py
from django import forms
from .models import Board, Comment    # Model Form 을 사용하기 위해 import 한다.

class BoardForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        max_length=20,
        widget=forms.TextInput(attrs={
            'class': 'title',
            'placeholder': 'Enter the title',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(attrs={
                'class': 'content-type',
                'rows': 5,
                'cols': 50,
                'placeholder': 'Enter the content',
            }
        )
    )

    class Meta:
        model = Board
        fields = ['title', 'content',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

agora/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Comment    # models.py 에 있는 Board 라는 class를 import 하겠다는 의미
from .forms import BoardForm, CommentForm
from django.core.paginator import Paginator # paging 을 하기 위해 사용
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model

def index(request):
    boards = Board.objects.all()[::-1]
    paginator = Paginator(boards, 5) # 한 페이지당 5개의 글을 보여주겠다
    page = request.GET.get('page')
    lists = paginator.get_page(page)
    context = {'boards': boards, 'lists': lists}
    return render(request, 'boards/index.html', context) # templates 안의 communication_boards 폴더에 있는 index.html을 랜더하겠다.

@login_required() # 로그인한 사람만 글을 쓸 수 있도록
def new(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():  # 유효성 검사
            board = form.save(commit=False)   # 잠시 저장되지 않게 함
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'boards/form.html', context)

def detail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    person = get_object_or_404(get_user_model(), pk=board.user.pk)  # 글쓴 사람
    comments = board.comments_rn.all()
    comment_form = CommentForm()
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'person': person
    }
    return render(request, 'boards/detail.html', context)


def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:  # 작성한 유저와 삭제요청을 한 유저가 같으면 조건문 실행
        if request.method == 'POST':
            board.delete()
            return redirect('boards:index')
        else:
            return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:index')

@login_required()
def edit(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                form.save()
                return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)
    else:
        return redirect('boards:index')
    context = {'board': board, 'form': form}
    return render(request, 'boards/form.html', context)


@login_required()
@require_POST   # POST 요청을 제외한 요청이 들어오면 405 에러가 뜬다
def comments_create(request, board_pk):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.board_id = board_pk
        comment.save()
    return redirect('boards:detail', board_pk)

@login_required()
def comments_edit(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                form.save()
                return redirect('boards:detail', board_pk)
        else:
            form = CommentForm(instance=comment)
    else:
        return redirect('boards:detail', board_pk)
    context = {'form': form, 'comment': comment}
    return render(request, 'boards/comment_edit.html', context)

@login_required()
@require_POST
def comments_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user:
        return redirect('boards:detail', board_pk)
    comment.delete()
    return redirect('boards:detail', board_pk)


@login_required()
def like(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.user in board.like_users.all(): # 이 게시글에 좋아요를 누른 유저 중 요청을 한 유저(request.user)가 있다면
        board.like_users.remove(request.user)  # 목록에서 지워준다. (즉 좋아요를 취소 한다는 의미)
    else:
        board.like_users.add(request.user)
    return redirect('boards:index')



# 팔로우 : 특정 대상을 팔로우하는 경우 그 대상의 소식을 만날 수 있습니다.
# 팔로워 : 나 또는 특정 대상을 팔로우하는 사람을 뜻합니다.
# 팔로잉 : 나 또는 특정 대상이 팔로우하는 사람을 뜻합니다.
@login_required()
def follow(request, board_pk, user_pk):
   person = get_object_or_404(get_user_model(), pk=user_pk)
   if request.user in person.followers.all():
       person.followers.remove(request.user)
   else:
       person.followers.add(request.user)
   return redirect('boards:detail', board_pk)

agora/mypage/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model


### 자신의 페이지
@login_required()
def userprofile(request, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)

    if not person.image:
        pic_url = ""
    else:
        pic_url = person.image.url
    context = {
        'id': person.username,
        'name': person.user_name,
        'date_of_birth': person.date_of_birth,
        'job': person.job,
        'gender': person.gender,
        'pic': pic_url,
        'text': person.text
    }
    return render(request, 'mypage/userprofile.html', context)

agora/boards/templates/boards/_board.html
<!-- index.html 에 아래 내용을 써도 좋지만 너무 길어지면 가독성이 떨어지기 때문에 모듈화 한다. -->
<div class="card-body">
    <a href="{% url 'boards:like' board.pk %}" class="card-link">
        {% if user in board.like_users.all %}
            <i class="fas fa-heart fa-lg" style="color:crimson"></i>
        {% else %}
            <i class="far fa-heart fa-lg" style="color:black"></i>
        {% endif %}
    </a>
    <p class="card-text"style="font-family: 'Do Hyeon', sans-serif;">{{ board.like_users.count }} 명이 좋아합니다</p>
</div>

agora/boards/templates/boards/_profile.html
<div class="jumbotron text-center text-white bg-dark">
   <p class="lead mb-1" style="font-family: 'Do Hyeon', sans-serif;">작성자 정보</p>
   <h2 class="display" style="font-family: 'Do Hyeon', sans-serif;">{{ board.user }}</h2>
   <hr class="border-white">
   <p class="lead" style="font-family: 'Do Hyeon', sans-serif;">
       팔로잉 : {{ person.followings.all | length }}
       팔로워 : {{ person.followers.all | length }}
   </p>
   {% if user != person %}
       {% if user in person.followers.all %}
   <!-- '웹 접근성' :  a 태그의 'role'속성은 시각장애인들을 위해 스크린리더가 읽어주는 속성이다. img의 alt 속성과 비슷? -->
           <a class='btn btn-primary' href="{% url 'boards:follow' board.pk person.pk %}" role="button" style="font-family: 'Do Hyeon', sans-serif;">Unfollow</a>
       {% else %}
           <a class='btn btn-primary' href="{% url 'boards:follow' board.pk person.pk %}" role="button" style="font-family: 'Do Hyeon', sans-serif;">Follow</a>
       {% endif %}
   {% endif %}
    <a class="btn btn-primary" href="{% url 'mypage:userprofile' person.pk %}" role="button" style="font-family: 'Do Hyeon', sans-serif;">유저페이지</a>
</div>

agora/boards/templates/boards/comment_edit.html
{% extends 'base.html '%}

{% block body %}
<h1 class="text-center" style="font-family: 'Do Hyeon', sans-serif;">Comment Edit</h1>
<hr>
{% if user.is_authenticated %}
    {% if comment.user == request.user %}
        <form action="{% url 'boards:comments_edit' comment.board.id comment.pk %}" method="POST" style="font-family: 'Do Hyeon', sans-serif;">
            {% csrf_token %}
            댓글 수정: <input type="text" name="content" value="{{ comment.content }} ">
            <input type="submit" value="댓글 수정">
        </form>
    {% endif %}
{% endif %}

{% endblock %}

agora/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block body %}

<h1 class="text-center" style="color:black;font-family: 'Do Hyeon', sans-serif;">{{ board.pk }}번 게시판 글</h1>
<hr>

<table class="table table-hover" bgcolor="Cornsilk" border=0px solid; style="table-layout: fixed">
    <thead>
        <tr>
            <th style="width:100px;font-family: 'Do Hyeon', sans-serif;" class="text-center">목록</th>
            <th style="width:500px;font-family: 'Do Hyeon', sans-serif;" class="text-center">내용</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 번호</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.pk }}</td>
    </tr>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 제목</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.title }}</td>
    </tr>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">작성 시각</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.created_at }}</td>
    </tr>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">수정 시각</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.updated_at }}</td>
    </tr>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 내용</td>
        <td class="text-center" style="word-break:break-all;font-family: 'Do Hyeon', sans-serif;" wrap="hard">{{ board.content }}</td>
    </tr>
    </tbody>
</table>

<center>

<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'boards:index' %}" style="font-family: 'Do Hyeon', sans-serif;"><input type="button" value="메인"></a>
    <!-- 글을 쓴 유저만 수정과 삭제가 가능하도록 조건을 걺  -->
    {% if user == board.user %}
        <a href="{% url 'boards:edit' board.pk %}" style="font-family: 'Do Hyeon', sans-serif;"><input type="button" value="수정"></a>
        <input type="submit" value="삭제" style="font-family: 'Do Hyeon', sans-serif;">
    {% endif %}
</form>

    <br>

</center>

{% include 'boards/_profile.html' %}

<center>
    <p><strong style="font-family: 'Do Hyeon', sans-serif;">댓글 목록 | 현재 댓글 갯수: {{ comments|length }} 개</strong></p>
    {% if user.is_authenticated %}
        {% for comment in comments %}
            <p><b><a href="{% url 'mypage:userprofile' comment.user.pk %}" style="font-family: 'Do Hyeon', sans-serif;">{{ comment.user }}</a> 님의 댓글 : {{ comment.content }}</b></p>
            {% if comment.user == request.user %}
                <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <a href="{% url 'boards:comments_edit' board.pk comment.pk %}" style="font-family: 'Do Hyeon', sans-serif;"><input type="button" value="댓글수정"></a>
                    <input type="submit" value="댓글삭제" style="font-family: 'Do Hyeon', sans-serif;">
                </form>
            {% endif %}
        {% empty %}
            <p style="font-family: 'Do Hyeon', sans-serif;">댓글이 없습니다. </p>
        {% endfor %}
    {% else %}
        <a href="{% url 'accounts:login' %}" style="font-family: 'Do Hyeon', sans-serif;">로그인이 필요합니다.</a>
    {% endif %}

</center>

<br>

<center>
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성" style="font-family: 'Do Hyeon', sans-serif;">
    </form>
</center>

<br>

{% endblock %}

agora/boards/templates/boards/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'new' %}
    <h1 align="center" style="font-family: 'Do Hyeon', sans-serif;">New</h1>
{% else %}
    <h1 align="center" style="font-family: 'Do Hyeon', sans-serif;">Edit</h1>
{% endif %}
<hr>



<form action="" method="post" style="font-family: 'Do Hyeon', sans-serif;">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "글작성" button_type='submit' button_class='btn-primary' %}

<!--    {{ form.as_p }}   &lt;!&ndash; form의 내용을 p 태그로 만들겠다. &ndash;&gt;-->
<!--    <input type="submit" value="등록">-->

    {% if request.resolver_match.url_name == 'new' %}    <!-- create -> new 로 바꿈 -->
        <a href="{% url 'boards:index' %}" class="btn btn-primary" style="font-family: 'Do Hyeon', sans-serif;">메인페이지</a>
    {% else %}
        <a href="{% url 'boards:detail' board.pk %}" class="btn btn-primary" style="font-family: 'Do Hyeon', sans-serif;">상세페이지</a>
    {% endif %}

</form>

{% endblock %}

agora/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block body %}

<h1 class="text-center" style="color:black">게시판</h1>
<hr>
<table class="table table-hover" bgcolor="Cornsilk ">
    <thead>
        <tr>
            <th class="text-center"style="font-family: 'Do Hyeon', sans-serif;">번호</th>
            <th class="text-center"style="font-family: 'Do Hyeon', sans-serif;">제목</th>
            <th class="text-center"style="font-family: 'Do Hyeon', sans-serif;">날짜</th>
            <th class="text-center"style="font-family: 'Do Hyeon', sans-serif;">수정날짜</th>
            <th class="text-center"style="font-family: 'Do Hyeon', sans-serif;">좋아요</th>
        </tr>
    </thead>
    {% for board in lists %}    <!-- communication_boards 에서 lists로 변경 -->
        <tbody>
            <tr>
                <td class="text-center"><a href="/boards/{{ board.pk }}/" style="font-family: 'Do Hyeon', sans-serif;">{{board.id}}</a></td>
                <td class="text-center"><a href="/boards/{{ board.pk }}/"style="font-family: 'Do Hyeon', sans-serif;">{{board.title}}</a> ({{ board.comments_rn.all | length }})</td>
                <td class="text-center"><a href="/boards/{{ board.pk }}/"style="font-family: 'Do Hyeon', sans-serif;">{{board.created_at}}</a></td>
                <td class="text-center"><a href="/boards/{{ board.pk }}/"style="font-family: 'Do Hyeon', sans-serif;">{{board.updated_at}}</a></td>
                <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">{% include 'boards/_board.html' %}</td>
            </tr>
        </tbody>

    {% endfor %}
</table>
<hr>


    {% if user.is_authenticated %}
        <a href="{% url 'boards:new' %}" style="font-family: 'Do Hyeon', sans-serif;"><input type="button" value="글작성"></a>
    {% else %}
        <a href="{% url 'accounts:login' %}" style="font-family: 'Do Hyeon', sans-serif;">로그인이 필요합니다</a>
    {% endif %}


<div class="pagination">
    <span class="step-links">
        {% if lists.has_previous %}
            <a href="?page=1" style="font-family: 'Do Hyeon', sans-serif;">[맨앞]</a>
            <a href="?page={{ lists.previous_page_number }}" style="font-family: 'Do Hyeon', sans-serif;">[이전]</a>
        {% endif %}

        <span class="current" style="font-family: 'Do Hyeon', sans-serif;">{{ lists.number}}</span>
        <span>/</span>
        <span style="font-family: 'Do Hyeon', sans-serif;">{{ lists.paginator.num_pages }}</span>

        {% if lists.has_next %}
            <a href="?page={{ lists.next_page_number }}" style="font-family: 'Do Hyeon', sans-serif;">[다음]</a>
            <a href="?page={{ lists.paginator.num_pages }}" style="font-family: 'Do Hyeon', sans-serif;">[맨뒤]</a>
        {% endif %}
    </span>
</div>

{% endblock %}

agora/boards/templates/boards/mypage.html
<br><br><br><br><br>

<h2 align="center">{{ name }}님의 페이지</h2>
<div align="center">
    <p>ID : {{ id }}</p>
    <p>pic : {{ pic_url }}</p>
    <p>이름 : {{ name }}</p>
    <p>생년월일 : {{ birthdate }}</p>
    <p>나이 : {{ age }}</p>
    <p>성별 : {{ gender }}</p>
</div>

agora/boards/templates/boards/table.html
{% comment %}
  totalCnt: <strong>{{ totalCnt }}</strong> current_page: <strong>{{ current_page }}</strong> boardList: <strong>{{ boardList|length }}</strong>
  {% endcomment %}

  <table cellspacing=1 width=700 border=0>
      <tr>
          <td style="font-family: 'Do Hyeon', sans-serif;">총 게시물수: {{ totalCnt }}</td>
          <td><p align=right style="font-family: 'Do Hyeon', sans-serif;"> 페이지:{{ current_page }}
          </td>
      </tr>
  </table>

  <table cellspacing=1 width=700 border=1>
      <tr>
          <td width=50><p align=center style="font-family: 'Do Hyeon', sans-serif;">번호</p></td>
          <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">이름</p></td>
          <td width=320><p align=center style="font-family: 'Do Hyeon', sans-serif;">제목</p></td>
          <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">등록일</p></td>
          <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">조회수</p></td>
      </tr>

      {% if boardList %}
          <ul>
              {% for boardRow in boardList %}
              <tr>
              <td width=50><p align=center style="font-family: 'Do Hyeon', sans-serif;">{{ boardRow.id }}</p></td>
              <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">{{ boardRow.name }}</p></td>
              <td width=320>
                  <p align=center>
                      <a href="/viewWork?memo_id={{ boardRow.id }}&current_page={{ current_page }}&searchStr=None" title="{{ boardRow.memo}}" style="font-family: 'Do Hyeon', sans-serif;">{{ boardRow.subject }}
                  </p>
              </td>
              <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">{{ boardRow.created_date }}</p></td>
              <td width=100><p align=center style="font-family: 'Do Hyeon', sans-serif;">{{ boardRow.hits }}</p></td>
              </tr>
              {% endfor %}
          </ul>
      {% else %}
          <p>No Data.</p>
      {% endif %}
  </table>

  <table cellspacing=1 width=700 border=1 >
      <tr> <td>
          {% for page in totalPageList %}
              <a href="/listSpecificPageWork?current_page={{page}}" >
              [
              {% ifequal page current_page %}
                  <b>
              {% endifequal %}
              {{page}}

              {% ifequal page current_page  %}
                  </b>
              {% endifequal %}
              ]
          {% endfor %}
          </td> </tr>
  </table>

  <table width=700>
      <tr>
          <td><input type=button value="글쓰기"  OnClick="window.location='/show_write_form'">    </td>
          <td><form name=searchf method=post action="/searchWithSubject/">
              <p align=right><input type=text name=searchStr size=50  maxlength=50>
              <input type=submit value="글찾기"></p>
          </td>
      </tr>
  </table>