agora/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password'),
]

agora/agora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('mypage/', include('mypage.urls')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('', views.index),
    path('parsed_data/', include('parsed_data.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agora/boards/urls.py
from django.urls import path
from . import views    # 동일한 디렉토리에 있는 views.py 를 import 하겠다.

# 여러 APP이 있을 경우 이름 공간을 분리하기 위해 아래와 같이 app의 이름을 지정한다.
# app_name 쓸 때 소문자로 써야함
app_name = 'boards'

# 경로 설정할 때 마지막에 꼭 '/' 가 들어가야 한다.
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name='comments_edit'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/like/', views.like, name='like'),
    path('<int:board_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

agora/chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

agora/mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('userprofile/<int:user_pk>/', views.userprofile, name='userprofile'),
]

agora/parsed_data/urls.py
from django.urls import path
from . import views    # 동일한 디렉토리에 있는 views.py 를 import 하겠다.
from django.conf import settings
from django.conf.urls.static import static

app_name = 'parsed_data'

urlpatterns = [
    path('', views.index, name='index'),
    path('GOV/', views.GOV, name='GOV'),
    path('ASSEM/', views.ASSEM, name='ASSEM'),
    path('ASSEM-REGU/', views.ASSEM_REGU, name='ASSEM_REGU'),
    path('GOV/<int:gov_pk>/', views.GOV_DETAIL, name='gov_detail'),
    path('ASSEM/<int:assem_pk>/', views.ASSEM_DETAIL, name='assem_detail'),
    path('ASSEM-REGU/<int:regu_pk>/', views.REGU_DETAIL, name='regu_detail'),
    ################################ GOV ###################################################
    path('GOV/<int:gov_pk>/ga_new/', views.ga_new, name='ga_new'),
    path('GOV/<int:gov_pk>/agree/<int:ga_pk>/', views.ga_agree, name='ga_agree'),
    path('GOV/<int:gov_pk>/gd_new/', views.gd_new, name='gd_new'),
    path('GOV/<int:gov_pk>/disagree/<int:gd_pk>/', views.ga_disagree, name='ga_disagree'),
    ################################# ASSEM ################################################
    path('ASSEM/<int:assem_pk>/aa_new/', views.aa_new, name='aa_new'),
    path('ASSEM/<int:assem_pk>/agree/<int:aa_pk>/', views.aa_agree, name='aa_agree'),
    path('ASSEM/<int:assem_pk>/ad_new/', views.ad_new, name='ad_new'),
    path('ASSEM/<int:assem_pk>/disagree/<int:ad_pk>/', views.aa_disagree, name='aa_disagree'),
    ################################## REGU ################################################
    path('ASSEM-REGU/<int:regu_pk>/ra_new/', views.ra_new, name='ra_new'),
    path('ASSEM-REGU/<int:regu_pk>/agree/<int:ra_pk>/', views.ra_agree, name='ra_agree'),
    path('ASSEM-REGU/<int:regu_pk>/rd_new/', views.rd_new, name='rd_new'),
    path('ASSEM-REGU/<int:regu_pk>/disagree/<int:rd_pk>/', views.ra_disagree, name='ra_disagree'),

    #################################################################################################
    path('<int:gov_pk>/like/', views.like, name='like'),
    path('<int:assem_pk>/like2/', views.like2, name='like2'),
    path('<int:regu_pk>/like3/', views.like3, name='like3'),
    path('<int:gov_pk>/unlike/', views.unlike, name='unlike'),
    path('<int:assem_pk>/unlike2/', views.unlike2, name='unlike2'),
    path('<int:regu_pk>/unlike3/', views.unlike3, name='unlike3'),

    ##############################  like  #############################################
    path('GOV/<int:gov_pk>/likepg/', views.likepg, name='likepg'),
    path('GOV/<int:gov_pk>/likepg2/', views.likepg2, name='likepg2'),
    path('ASSEM/<int:assem_pk>/likepa/', views.likepa, name='likepa'),
    path('ASSEM/<int:assem_pk>/likepa2/', views.likepa2, name='likepa2'),
    path('ASSEM-REGU/<int:regu_pk>/likepar/', views.likepar, name='likepar'),
    path('ASSEM-REGU/<int:regu_pk>/likepar2/', views.likepar2, name='likepar2'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agora/parsed_data/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import RawData, LawData, ReguData, Pg_Board, Pg_Comment, Pg_Board2, Pg_Comment2, Pa_Board, Pa_Board2, Pa_Comment, Pa_Comment2,Par_Board, Par_Board2, Par_Comment, Par_Comment2, NumData, LawNum,ReguNum
from .forms import Pg_BoardForm, Pg_CommentForm, Pg_BoardForm2, Pg_CommentForm2, Pa_BoardForm, Pa_BoardForm2, Pa_CommentForm, Pa_CommentForm2, Par_BoardForm, Par_BoardForm2, Par_CommentForm, Par_CommentForm2


from django.core.paginator import Paginator # paging 을 하기 위해 사용
from django.contrib.auth.decorators import login_required

@login_required()
def index(request):
    return render(request, 'parsed_data/index.html')

@login_required()
def GOV(request):
    Raws = RawData.objects.all()[::-1]
    raw_num = NumData.objects.all()[::-1]

    paginator = Paginator(Raws, 10)
    page = request.GET.get('page')
    Raws_lists = paginator.get_page(page)

    paginator2 = Paginator(raw_num, 10)
    page2 = request.GET.get('page')
    raw_num_lists = paginator2.get_page(page2)


    context = {'Raws': Raws, 'Raws_lists': Raws_lists,'raw_num':raw_num,'raw_num_lists':raw_num_lists}
    return render(request, 'parsed_data/GOV.html', context)


@login_required()
def ASSEM(request):
    Laws = LawData.objects.all()[::-1]
    law_num = LawNum.objects.all()[::-1]
    paginator = Paginator(Laws, 10)
    page = request.GET.get('page')
    Laws_lists = paginator.get_page(page)

    paginator2 = Paginator(law_num, 10)
    page2 = request.GET.get('page')
    law_num_lists = paginator2.get_page(page2)

    context = {'Laws': Laws, 'Laws_lists': Laws_lists, 'law_num':law_num,'law_num_lists':law_num_lists}
    return render(request, 'parsed_data/ASSEM.html', context)


@login_required()
def ASSEM_REGU(request):
    Regus = ReguData.objects.all()[::-1]
    regu_num = ReguNum.objects.all()[::-1]
    paginator = Paginator(Regus, 10)
    page = request.GET.get('page')
    Regus_lists = paginator.get_page(page)

    paginator2 = Paginator(regu_num, 10)
    page2 = request.GET.get('page')
    regu_num_lists = paginator2.get_page(page2)

    context = {'Regus': Regus, 'Regus_lists': Regus_lists, 'regu_num':regu_num,'regu_num_lists':regu_num_lists}
    return render(request, 'parsed_data/ASSEM_REGU.html', context)


@login_required()
def GOV_DETAIL(request, gov_pk):
    raw = get_object_or_404(RawData, pk=gov_pk)

    boards = Pg_Board.objects.all()[::-1]

    boardcount = Pg_Board.objects.count()
    board_list = Pg_Board.objects.all().order_by('id')

    paginator = Paginator(boards, 5)
    page = request.GET.get('page')
    raw_lists = paginator.get_page(page)

    boards2 = Pg_Board2.objects.all()[::-1]

    boardcount2 = Pg_Board2.objects.count()
    board_list2 = Pg_Board2.objects.all().order_by('id')

    paginator2 = Paginator(boards2, 5)
    page2 = request.GET.get('page')
    raw_lists2 = paginator2.get_page(page2)


    context = {'raw': raw, 'boardcount': boardcount, 'board_list':board_list, 'boards':boards,
               'boardcount2': boardcount2, 'board_list2':board_list2, 'boards2':boards2,'raw_lists':raw_lists,"raw_lists2":raw_lists2}
    return render(request, 'parsed_data/gov_detail.html', context)

@login_required()
def ASSEM_DETAIL(request, assem_pk):
    law = get_object_or_404(LawData, pk=assem_pk)
    boards = Pa_Board.objects.all()[::-1]
    boardcount = Pa_Board.objects.count()
    board_list = Pa_Board.objects.all().order_by('id')
    paginator = Paginator(boards, 5)
    page = request.GET.get('page')
    law_lists = paginator.get_page(page)

    boards2 = Pa_Board2.objects.all()[::-1]
    boardcount2 = Pa_Board2.objects.count()
    board_list2 = Pa_Board2.objects.all().order_by('id')
    paginator2 = Paginator(boards2, 5)
    page2 = request.GET.get('page')
    law_lists2 = paginator2.get_page(page2)

    context = {'law': law, 'boardcount': boardcount, 'board_list': board_list, 'boards':boards,
               'boardcount2': boardcount2, 'board_list2': board_list2, 'boards2':boards2,'law_lists':law_lists,"law_lists2":law_lists2}
    return render(request, 'parsed_data/assem_detail.html', context)

@login_required()
def REGU_DETAIL(request, regu_pk):
    regu = get_object_or_404(ReguData, pk=regu_pk)

    boards = Par_Board.objects.all()[::-1]
    boardcount = Par_Board.objects.count()
    board_list = Par_Board.objects.all().order_by('id')
    paginator = Paginator(boards, 5)
    page = request.GET.get('page')
    regu_lists = paginator.get_page(page)

    boards2 = Par_Board2.objects.all()[::-1]
    boardcount2 = Par_Board2.objects.count()
    board_list2 = Par_Board2.objects.all().order_by('id')
    paginator2 = Paginator(boards2, 5)
    page2 = request.GET.get('page')
    regu_lists2 = paginator2.get_page(page2)


    context = {'regu': regu, 'boardcount': boardcount, 'board_list': board_list, 'boards':boards,
               'boardcount2': boardcount2, 'board_list2': board_list2, 'boards2':boards2,'regu_lists':regu_lists,"regu_lists2":regu_lists2}
    return render(request, 'parsed_data/regu_detail.html', context)

################################ GOV ###################################################

@login_required() # 로그인한 사람만 글을 쓸 수 있도록
def ga_new(request, gov_pk):
    raw = get_object_or_404(RawData, pk=gov_pk)
    if request.method == 'POST':
        form = Pg_BoardForm(request.POST, request.FILES)
        if form.is_valid():  # 유효성 검사
            board = form.save(commit=False)   # 잠시 저장되지 않게 함
            board.user = request.user
            board.save()
            return redirect('parsed_data:ga_agree', gov_pk, board.pk)
    else:
        form = Pg_BoardForm()
    context = {'form': form, 'raw': raw}
    return render(request, 'parsed_data/R_form.html', context)

@login_required()
def ga_agree(request, gov_pk, ga_pk):
    raw = get_object_or_404(RawData, pk=gov_pk)
    board = get_object_or_404(Pg_Board, pk=ga_pk)
    person = get_object_or_404(get_user_model(), pk=board.user.pk)  # 글쓴 사람
    comments = board.pd_comments.all()
    comment_form = Pg_CommentForm()
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'person': person,
        'raw':raw,
    }
    return render(request, 'parsed_data/ga_a_detail.html', context)

@login_required() # 로그인한 사람만 글을 쓸 수 있도록
def gd_new(request, gov_pk):
    raw = get_object_or_404(RawData, pk=gov_pk)
    if request.method == 'POST':
        form = Pg_BoardForm2(request.POST, request.FILES)
        if form.is_valid():  # 유효성 검사
            board = form.save(commit=False)   # 잠시 저장되지 않게 함
            board.user = request.user
            board.save()
            return redirect('parsed_data:ga_disagree', gov_pk, board.pk)
    else:
        form = Pg_BoardForm2()
    context = {'form': form, 'raw':raw}
    return render(request, 'parsed_data/R_form.html', context)

@login_required()
def ga_disagree(request, gov_pk, gd_pk):
    raw = get_object_or_404(RawData, pk=gov_pk)
    board = get_object_or_404(Pg_Board2, pk=gd_pk)
    person = get_object_or_404(get_user_model(), pk=board.user.pk)  # 글쓴 사람
    comments = board.pd_comments2.all()
    comment_form = Pg_CommentForm2()
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'person': person,
        'raw':raw,
    }
    return render(request, 'parsed_data/ga_d_detail.html', context)

################################# ASSEM ################################################

@login_required() # 로그인한 사람만 글을 쓸 수 있도록
def aa_new(request, assem_pk):
    law = get_object_or_404(LawData, pk=assem_pk)
    if request.method == 'POST':
        form = Pa_BoardForm(request.POST, request.FILES)
        if form.is_valid():  # 유효성 검사
            board = form.save(commit=False)   # 잠시 저장되지 않게 함
            board.user = request.user
            board.save()
            return redirect('parsed_data:aa_agree', assem_pk, board.pk)
    else:
        form = Pa_BoardForm()
    context = {'form': form, 'law':law}
    return render(request, 'parsed_data/La_form.html', context)

@login_required()
def aa_agree(request, assem_pk, aa_pk):
    law = get_object_or_404(LawData, pk=assem_pk)
    board = get_object_or_404(Pa_Board, pk=aa_pk)
    person = get_object_or_404(get_user_model(), pk=board.user.pk)  # 글쓴 사람
    comments = board.pa_comments.all()
    comment_form = Pa_CommentForm()
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'person': person,
        'law':law,
    }
    return render(request, 'parsed_data/aa_a_detail.html', context)

@login_required() # 로그인한 사람만 글을 쓸 수 있도록
def ad_new(request, assem_pk):
    law = get_object_or_404(LawData, pk=assem_pk)
    if request.method == 'POST':
        form = Pa_BoardForm2(request.POST, request.FILES)
        if form.is_valid():  # 유효성 검사
            board = form.save(commit=False)   # 잠시 저장되지 않게 함
            board.user = request.user
            board.save()
            return redirect('parsed_data:aa_disagree', assem_pk, board.pk)
    else:
        form = Pa_BoardForm2()
    context = {'form': form, 'law':law}
    return render(request, 'parsed_data/La_form.html', context)

@login_required()
def aa_disagree(request, assem_pk, ad_pk):
    law = get_object_or_404(LawData, pk=assem_pk)
    board = get_object_or_404(Pa_Board2, pk=ad_pk)
    person = get_object_or_404(get_user_model(), pk=board.user.pk)  # 글쓴 사람
    comments = board.pa_comments2.all()
    comment_form = Pa_CommentForm2()
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
        'person': person,
        'law':law,
    }
    return render(request, 'parsed_data/aa_d_detail.html', context)

################################## REGU ################################################

@login_required() # 로그인한 사람만 글을 쓸 수 있도록

agora/parsed_data/templates/parsed_data/La_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{%load static%}
{% block body %}

{% if request.resolver_match.url_name == 'aa_new' %}
    <h1 align="center">New</h1>
{% elif request.resolver_match.url_name == 'ad_new' %}
    <h1 align="center">New</h1>
{% else %}
    <h1 align="center">Edit</h1>
{% endif %}
<hr>



<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "글작성" button_type='submit' button_class='btn-primary' %}

<!--    {{ form.as_p }}   &lt;!&ndash; form의 내용을 p 태그로 만들겠다. &ndash;&gt;-->
<!--    <input type="submit" value="등록">-->

    {% if request.resolver_match.url_name == 'new' %}    <!-- create -> new 로 바꿈 -->
        <a href="{% url 'parsed_data:index' %}" class="btn btn-primary">메인페이지</a>
    {% else %}
        <a href="#" class="btn btn-primary">상세페이지</a>
    {% endif %}

</form>
{% endblock %}

agora/parsed_data/templates/parsed_data/aa_a_detail.html
{% extends 'base.html' %}

{% block body %}

<h1 class="text-center" style="font-family: 'Do Hyeon', sans-serif;">국회 입법현황 찬성 {{ board.pk }}번 게시판 글</h1>
<hr>

<table class="table table-hover" bgcolor="Cornsilk" border=0px solid; style="table-layout: fixed">
    <thead>
        <tr>
            <th style="width:100px;font-family: 'Do Hyeon', sans-serif;" class="text-center">목록</th>
            <th style="width:500px;font-family: 'Do Hyeon', sans-serif;" class="text-center">내용</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">글 번호</td>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">{{ board.pk }}</td>
    </tr>
    <tr>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">글 제목</td>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">{{ board.title }}</td>
    </tr>

    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 내용</td>
        <td class="text-center" style="word-break:break-all;font-family: 'Do Hyeon', sans-serif;" wrap="hard">{{ board.content }}</td>
    </tr>
    </tbody>
</table>
<a href="/parsed_data/ASSEM/{{law.id}}" class="btn btn-primary"style="font-family: 'Do Hyeon', sans-serif;">뒤로</a>
<!--
<center>

<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'boards:index' %}"><input type="button" value="메인"></a>-->
    <!-- 글을 쓴 유저만 수정과 삭제가 가능하도록 조건을 걺  -->
<!--
    {% if user == board.user %}
        <a href="{% url 'boards:edit' board.pk %}"><input type="button" value="수정"></a>
        <input type="submit" value="삭제">
    {% endif %}
</form>
</center>
-->

{% include 'boards/_profile.html' %}
<!--
<center>
    <p><strong>댓글 목록 | 현재 댓글 갯수: {{ comments|length }} 개</strong></p>
    {% if user.is_authenticated %}
        {% for comment in comments %}
            <p><b><a href="{% url 'mypage:userprofile' comment.user.pk %}">{{ comment.user }}</a> 님의 댓글 : {{ comment.content }}</b></p>
            {% if comment.user == request.user %}
                <a href="{% url 'boards:comments_edit' board.pk comment.pk %}"><input type="button" value="댓글수정"></a>
                <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="댓글삭제">
                </form>
            {% endif %}
        {% empty %}
            <p>댓글이 없습니다. </p>
        {% endfor %}
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인이 필요합니다.</a>
    {% endif %}

</center>


<center>
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성">
    </form>
</center>
-->
{% endblock %}

agora/parsed_data/templates/parsed_data/aa_d_detail.html
{% extends 'base.html' %}

{% block body %}

<h1 class="text-center" style="font-family: 'Do Hyeon', sans-serif;">국회 입법현황 반대 {{ board.pk }}번 게시판 글</h1>
<hr>

<table class="table table-hover" bgcolor="Cornsilk" border=0px solid; style="table-layout: fixed">
    <thead>
        <tr>
            <th style="width:100px;font-family: 'Do Hyeon', sans-serif;" class="text-center">목록</th>
            <th style="width:500px;font-family: 'Do Hyeon', sans-serif;" class="text-center">내용</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">글 번호</td>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">{{ board.pk }}</td>
    </tr>
    <tr>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">글 제목</td>
        <td class="text-center"style="font-family: 'Do Hyeon', sans-serif;">{{ board.title }}</td>
    </tr>

    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 내용</td>
        <td class="text-center" style="word-break:break-all;font-family: 'Do Hyeon', sans-serif;" wrap="hard">{{ board.content }}</td>
    </tr>
    </tbody>
</table>
<a href="/parsed_data/ASSEM/{{law.id}}" class="btn btn-primary"style="font-family: 'Do Hyeon', sans-serif;">뒤로</a>
<!--
<center>

<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'boards:index' %}"><input type="button" value="메인"></a>-->
    <!-- 글을 쓴 유저만 수정과 삭제가 가능하도록 조건을 걺  -->
<!--
    {% if user == board.user %}
        <a href="{% url 'boards:edit' board.pk %}"><input type="button" value="수정"></a>
        <input type="submit" value="삭제">
    {% endif %}
</form>
</center>
-->

{% include 'boards/_profile.html' %}
<!--
<center>
    <p><strong>댓글 목록 | 현재 댓글 갯수: {{ comments|length }} 개</strong></p>
    {% if user.is_authenticated %}
        {% for comment in comments %}
            <p><b><a href="{% url 'mypage:userprofile' comment.user.pk %}">{{ comment.user }}</a> 님의 댓글 : {{ comment.content }}</b></p>
            {% if comment.user == request.user %}
                <a href="{% url 'boards:comments_edit' board.pk comment.pk %}"><input type="button" value="댓글수정"></a>
                <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="댓글삭제">
                </form>
            {% endif %}
        {% empty %}
            <p>댓글이 없습니다. </p>
        {% endfor %}
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인이 필요합니다.</a>
    {% endif %}

</center>


<center>
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성">
    </form>
</center>
-->
{% endblock %}

agora/parsed_data/templates/parsed_data/ga_d_detail.html
{% extends 'base.html' %}

{% block body %}

<h1 class="text-center" style="font-family: 'Do Hyeon', sans-serif;">정부 입법현황 반대 {{ board.pk }}번 게시판 글</h1>
<hr>

<table class="table table-hover" bgcolor="Cornsilk" border=0px solid; style="table-layout: fixed">
    <thead>
        <tr>
            <th style="width:100px;font-family: 'Do Hyeon', sans-serif;" class="text-center">목록</th>
            <th style="width:500px;font-family: 'Do Hyeon', sans-serif;" class="text-center">내용</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 번호</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.pk }}</td>
    </tr>
    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 제목</td>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">{{ board.title }}</td>
    </tr>

    <tr>
        <td class="text-center" style="font-family: 'Do Hyeon', sans-serif;">글 내용</td>
        <td class="text-center" style="word-break:break-all;font-family: 'Do Hyeon', sans-serif;" wrap="hard">{{ board.content }}</td>
    </tr>
    </tbody>
</table>
<a href="/parsed_data/GOV/{{raw.id}}" class="btn btn-primary" style="font-family: 'Do Hyeon', sans-serif;">뒤로</a>




<!--
<center>

<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'boards:index' %}"><input type="button" value="메인"></a>-->
    <!-- 글을 쓴 유저만 수정과 삭제가 가능하도록 조건을 걺  -->
<!--
    {% if user == board.user %}
        <a href="{% url 'boards:edit' board.pk %}"><input type="button" value="수정"></a>
        <input type="submit" value="삭제">
    {% endif %}
</form>
</center>
-->

{% include 'boards/_profile.html' %}


<!--
<center>
    <p><strong>댓글 목록 | 현재 댓글 갯수: {{ comments|length }} 개</strong></p>
    {% if user.is_authenticated %}
        {% for comment in comments %}
            <p><b><a href="{% url 'mypage:userprofile' comment.user.pk %}">{{ comment.user }}</a> 님의 댓글 : {{ comment.content }}</b></p>
            {% if comment.user == request.user %}
                <a href="{% url 'boards:comments_edit' board.pk comment.pk %}"><input type="button" value="댓글수정"></a>
                <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="댓글삭제">
                </form>
            {% endif %}
        {% empty %}
            <p>댓글이 없습니다. </p>
        {% endfor %}
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인이 필요합니다.</a>
    {% endif %}

</center>


<center>
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성">
    </form>
</center>
-->
{% endblock %}