agora/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password'),
]

agora/agora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('mypage/', include('mypage.urls')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('', views.index),
    path('parsed_data/', include('parsed_data.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agora/chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

agora/mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('userprofile/<int:user_pk>/', views.userprofile, name='userprofile'),
]

agora/parsed_data/urls.py
from django.urls import path
from . import views    # 동일한 디렉토리에 있는 views.py 를 import 하겠다.
from django.conf import settings
from django.conf.urls.static import static

app_name = 'parsed_data'

urlpatterns = [
    path('', views.index, name='index'),
    path('GOV/', views.GOV, name='GOV'),
    path('ASSEM/', views.ASSEM, name='ASSEM'),
    path('ASSEM-REGU/', views.ASSEM_REGU, name='ASSEM_REGU'),
    path('GOV/<int:gov_pk>/', views.GOV_DETAIL, name='gov_detail'),
    path('ASSEM/<int:assem_pk>/', views.ASSEM_DETAIL, name='assem_detail'),
    path('ASSEM-REGU/<int:regu_pk>/', views.REGU_DETAIL, name='regu_detail'),
    ################################ GOV ###################################################
    path('GOV/<int:gov_pk>/ga_new/', views.ga_new, name='ga_new'),
    path('GOV/<int:gov_pk>/agree/<int:ga_pk>/', views.ga_agree, name='ga_agree'),
    path('GOV/<int:gov_pk>/gd_new/', views.gd_new, name='gd_new'),
    path('GOV/<int:gov_pk>/disagree/<int:gd_pk>/', views.ga_disagree, name='ga_disagree'),
    ################################# ASSEM ################################################
    path('ASSEM/<int:assem_pk>/aa_new/', views.aa_new, name='aa_new'),
    path('ASSEM/<int:assem_pk>/agree/<int:aa_pk>/', views.aa_agree, name='aa_agree'),
    path('ASSEM/<int:assem_pk>/ad_new/', views.ad_new, name='ad_new'),
    path('ASSEM/<int:assem_pk>/disagree/<int:ad_pk>/', views.aa_disagree, name='aa_disagree'),
    ################################## REGU ################################################
    path('ASSEM-REGU/<int:regu_pk>/ra_new/', views.ra_new, name='ra_new'),
    path('ASSEM-REGU/<int:regu_pk>/agree/<int:ra_pk>/', views.ra_agree, name='ra_agree'),
    path('ASSEM-REGU/<int:regu_pk>/rd_new/', views.rd_new, name='rd_new'),
    path('ASSEM-REGU/<int:regu_pk>/disagree/<int:rd_pk>/', views.ra_disagree, name='ra_disagree'),

    #################################################################################################
    path('<int:gov_pk>/like/', views.like, name='like'),
    path('<int:assem_pk>/like2/', views.like2, name='like2'),
    path('<int:regu_pk>/like3/', views.like3, name='like3'),
    path('<int:gov_pk>/unlike/', views.unlike, name='unlike'),
    path('<int:assem_pk>/unlike2/', views.unlike2, name='unlike2'),
    path('<int:regu_pk>/unlike3/', views.unlike3, name='unlike3'),

    ##############################  like  #############################################
    path('GOV/<int:gov_pk>/likepg/', views.likepg, name='likepg'),
    path('GOV/<int:gov_pk>/likepg2/', views.likepg2, name='likepg2'),
    path('ASSEM/<int:assem_pk>/likepa/', views.likepa, name='likepa'),
    path('ASSEM/<int:assem_pk>/likepa2/', views.likepa2, name='likepa2'),
    path('ASSEM-REGU/<int:regu_pk>/likepar/', views.likepar, name='likepar'),
    path('ASSEM-REGU/<int:regu_pk>/likepar2/', views.likepar2, name='likepar2'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agora/agora/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AGORA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="shortcut icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 600px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #F8F8FF;
      height: auto;


    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 700px) {
      .sidenav {
        height: auto;
        padding: 15px;
        position: auto;
      }
      .row.content {height:auto;}
    }

  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a href="/" class="navbar-left"><img src="{% static 'images/a2.png' %}" height="43px;" style="padding-top: 5px; padding-right: 20px;" prefix="True"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a style="font-family: 'Do Hyeon', sans-serif;" href="{% url 'parsed_data:index' %}">Home</a></li>
        <li><a style="font-family: 'Do Hyeon', sans-serif;" href="/main/#about">About</a></li>
        <li><a style="font-family: 'Do Hyeon', sans-serif;" href="/boards/">자유게시판</a></li>
        <li><a style="font-family: 'Do Hyeon', sans-serif;" href="/parsed_data/">입법현황</a></li>
        <li><a style="font-family: 'Do Hyeon', sans-serif;" href="/main/#contact">Contact</a></li>
        {% if user.is_authenticated %}
            <li><a style="font-family: 'Do Hyeon', sans-serif;" href="{% url 'mypage:userprofile' user.pk %}">마이페이지</a></li>
        {% endif %}
      </ul>

      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="post" style="float:left; padding-top:10px;padding-right:10px;font-family: 'Do Hyeon', sans-serif;">
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="로그아웃">
            </form>

            <form action="{% url 'accounts:delete' %}" method="post" style="float:left;padding-top:10px;padding-right:10px;font-family: 'Do Hyeon', sans-serif;">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="회원탈퇴">
            </form>

          {% else %}
            <a class="btn btn-primary" href="{% url 'accounts:login' %}" style="padding-right:10px;font-family: 'Do Hyeon', sans-serif;">[로그인]</a>
            <a class="btn btn-success" href="{% url 'accounts:signup' %}" style="padding-right:10px;font-family: 'Do Hyeon', sans-serif;">[회원가입]</a>
          {% endif %}

      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content" >
    <div class="col-sm-2 sidenav" >
      <p><a class="btn btn-warning btn-block" style="font-family: 'Do Hyeon', sans-serif;" href="{% url 'parsed_data:GOV' %}">정부입법현황</a></p>
      <p><a class="btn btn-success btn-block" style="font-family: 'Do Hyeon', sans-serif;" href="{% url 'parsed_data:ASSEM' %}">국회입법현황</a></p>
      <p><a class="btn btn-primary btn-block" style="font-family: 'Do Hyeon', sans-serif;" href="{% url 'parsed_data:ASSEM_REGU' %}">국회입법현황(규제관련)</a></p>
    </div>
    <div class="col-sm-8 text-left" style="background-color: #f1f1f1;">
            {%block body%}
            {%endblock%}
    </div>
    {% if user.is_authenticated %}
    <div class="user-info">
      <h3 style="font-family: 'Do Hyeon', sans-serif;">안녕하세요! {{ user.username }} 님</h3>
      <a href="{% url 'accounts:edit' %}"><input class="btn btn-button" type="button"style="font-family: 'Do Hyeon', sans-serif;" value="회원정보 수정"></a>
      <a href="{% url 'accounts:change_password' %}"><input class="btn btn-button" type="button" style="font-family: 'Do Hyeon', sans-serif;" value="비밀번호 수정"></a>
    </div>
    {% endif %}
  </div>
</div>

<footer class="container-fluid text-center">
  <p>AGORA Copyright.</p>
</footer>

</body>
</html>